### ISSUE TITLE
Add prettier configuration for unified formatting of the code.

### ISSUE THREAD

**Issue by lime008** [PlatformOfTrust/multi-connector#2]
Right now there's a lot of formatting inconsistencies between the files and even inside some files that will make contributions to the project harder. Also using strict formatting rules will make the code review and merging pull requests easier.

**Comment by hoanvancs** [comment]
@lime008 I think you're pointing out a need for improvement in coding style. I would very much appreciate it if you give more suggestions such as using the `eslint` config, etc.

**Comment by lime008** [comment]
@hoanvancs I'll create a pull request with the suggested configs based on the current coding style.

**Comment by lime008** [comment]
@hoanvancs 

As a change to the current coding style I would add dangling comma enforcement for multiline statements so in a case a value is added there's going to be just one line change in a commit rather than a change on the previous line ( addition of the comma ) and the new line.

Also there's a question about forcing semicolons or removing them from the code base. Right now the usage is mixed. Primary code style seems to use them though. So I'll force the use of semicolons for now.

**Comment by hoanvancs** [comment]
@PlatformOfTrust/connectors Hi all. Here is Lime from the Holda Technologies. We are discussing coding style improvement and find some way to make this project more standard. Could you please take a bit of time to join the conversation?

**Comment by kyyberi** [comment]
Sounds like it's time to fix some practices and document as requirements in commonly accessible public location in the web.
